version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: conf.py

formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
